# This is a basic workflow to help you get started with Actions

name: Build Docker Images

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build Docker Images
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Docker
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
      
      # Build CI Image
      - name: Build pi-pico-ci
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          target: ci
          push: false
          tags: pi-pico-ci:lasest
            
      # Build CI Image
      - name: Build pi-pico-dev
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          target: dev
          push: false
          tags: pi-pico-dev:lasest
