# This is a basic workflow that is manually triggered

name: Publish Docker Images

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

   # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Docker
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
        
      # Login against a ghcr registry
      - name: Log into registry ${{ env.REGISTRY }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
      # Build and Push CI Image
      - name: Build and Push pi-pico-ci
        run: |
          docker build --target=ci -t pi-pico-ci:latest .
          docker push ghcr.io/nick-dean/pi-pico-ci:latest
            
      # Build and Push dev Image
      - name: Build and Push pi-pico-dev
        run: |
          docker build --target=dev -t pi-pico-dev:latest .
          docker push ghcr.io/nick-dean/pi-pico-dev:latest
